version: '3.8'

services:

  web:
    build: ./
    image: irinaexcellent/ai-service:latest
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./:/usr/src/app